### ISSUE TITLE
Better error handling?

### ISSUE THREAD

**Issue by ghost** [mayoral/telegrammer#13]
I have noticed that all failures of communicating with the api return the same exception as the following. I get this same error message if the bot token is invalid, or the parameters are missing, or any other issue. is it possible to provide better error handling?

```
wrong number of arguments (1 for 2)
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer.rb:48:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/api_response.rb:18:in `exception'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/api_response.rb:18:in `fail'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/api_response.rb:18:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/bot.rb:469:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/bot.rb:469:in `api_request'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/bot.rb:488:in `send_something'
/app/vendor/bundle/ruby/2.0.0/gems/telegrammer-0.5.0/lib/telegrammer/bot.rb:198:in `send_photo'
/app/app/models/message.rb:47:in `send_photo'
/app/app/models/message.rb:31:in `dispatch_message'
/app/app/workers/delivery_worker.rb:15:in `perform'
```

**Comment by mayoral** [comment]
You're totally right. There was a little bug raising the exceptions. It's now fixing, and I'm in the process to release 0.5.1 with that fixed.

Thanks for reporting this bug! :)

**Comment by ghost** [comment]
great thanks! looking forward to it.
